### ISSUE TITLE
Hanging on "[+] Got message from Agent at"

### ISSUE THREAD

**Issue by n0clues** [sensepost/liniaal#1]
Hi, I've got a problem (probably with stager but I'm not sure how can I debug).

First of all I don't know how did it work for you ;> because you completely ignore the _URL_ option (I had to add one line in _checkOptions()_), other problem was with my SSL cert but I added new _Transport_ object to the http client with _InsecureSkipVerify_ set to _true_.

Anyway after that I was able to run liniaal. I've got listening Empire http_mapi:
![obraz](https://user-images.githubusercontent.com/5691550/29124868-68c43194-7d1a-11e7-997c-a9f56c687721.png)

then I run liniaal:
 
![obraz](https://user-images.githubusercontent.com/5691550/29124949-ab5e0a2a-7d1a-11e7-8478-eea8903d2835.png)

then I run empire's http_mapi launcher on a victim machine.

After that I see 

> [+] Got message from Agent at: 09/08/2017 03:40:21

where the time you see above is still updating. 

I added few _output()_ in _getMessage()_ function do debug this and I see that liniaal is receiving the messages over and over which are the same: 

the _messageSubject_ is 

> mailpireout 

and the payload is 

> PMSTAGE - #base64-here#

Maybe do you have some idea what can be wrong? Thanks!

P.S.: really nice research!
P.S.2: when I will be able to test everything properly I'm going to pull the modifications I mentioned before.

**Comment by staaldraad** [comment]
Hi!
Firstly, thanks for trying it out! Didn't think anyone would :+1: 

Thanks
-------
You are absolutely right, the URL wasn't being set, in my rush to get it ready for the Troopers talk, I didn't test with URL. My test domains were all auto resolving, hence the missed URL. 
Same with the HTTPS, I relied on _InsecureSkipVerify_ being set in the upstream Ruler library, but that is only for autodiscover.

^ A PR of your changes will be very welcome!

Real issue
------

I've been trying to reproduce on my side. 

Setup:
*liniaal* - Master (with an added ```output(string(payload))``` )
*Empire* - Master (commit - 37c72f0428d68edc36d4e19ee3540770ef12d981)

For http_mapi - I'm using the one that has been merged into Empire (although this should be the same as in the liniaal repo)

In Empire:
```
  Name              Required    Value                            Description
  ----              --------    -------                          -----------
  KillDate          False                                        Date for the listener to exit (MM/dd/yyyy).
  Name              True        mapi                             Name for the listener.
  DefaultProfile    True        /admin/get.php,/news.php,/login/ Default communication profile for the agent.
                                process.php|Mozilla/5.0 (Windows
                                NT 6.1; WOW64; Trident/7.0;
                                rv:11.0) like Gecko
  DefaultLostLimit  True        60                               Number of missed checkins before exiting
  DefaultDelay      True        20                               Agent delay/reach back interval (in seconds).
  Host              True        http://172.17.0.2:8080           Hostname/IP for staging.
  Email             False                                        The email address of our target
  WorkingHours      False                                        Hours for the agent to operate (09:00-17:00).
  CertPath          False                                        Certificate path for https listeners.
  DefaultJitter     True        0.0                              Jitter in agent reachback interval (0.0-1.0).
  Folder            True        Liniaal                          The hidden folder in Exchange to user
  Port              True        8080                             Port for the listener.
  BindIP            True        0.0.0.0                          The IP to bind to on the control server.
  StagingKey        True        6zA*LktHfhMxQ#-RIv97g0;C@Fm2Uj.K Staging key for initial agent negotiation.
  ServerVersion     True        Microsoft-IIS/7.5                TServer header for the control server.
```

In Liniaal

```
> set EmailAddress xxxx@xxx.com
> set Password yyy@yyy.com
> set Host http://172.17.0.2:8080
> execute

```
For the launcher, I've taken the one from Empire and removed ```-NoP -sta -NonI -W Hidden``` (so I can see if something breaks) - And executed on my target

![screenshot from 2017-08-09 16-40-35](https://user-images.githubusercontent.com/4200832/29127775-f800e34e-7d19-11e7-9866-76df8016aa9f.png)

Finding Possible Issues
---------

* Running the launcher without ```-NoP -sta -NonI -W Hidden``` could help show up issues in the powershell. Maybe there is something killing the powershell?

* Starting Empire with ```--debug 2``` would show errors that might be occurring during the staging

![screenshot from 2017-08-09 16-52-39](https://user-images.githubusercontent.com/4200832/29128102-d3283526-7d1a-11e7-805c-fec21ddfd0a9.png)

* Possible that there are multiple-mailboxes (although you are getting the stage, so I doubt this is it)


I'm going to try another domain and think of a few other issues that might be causing this.

Thanks again for trying it out, having the patience to find a fix for my omissions and finally putting together a detailed issue.

**Comment by staaldraad** [comment]
Oh and another thing to try,

You can flush the message folder, it could be that there are a few messages hanging around and they are causing sync issues between empire and the agent.

with Liniaal:
```
flush           remove all messages currently in the hidden folder
> flush
```
This should clear out all the messages. And you can try the launcher again

**Comment by n0clues** [comment]
I didn't suspect so quick answer! Thank you.

Tomorrow morning I will try to reproduce your moves step by step.

I forgot to mention that I use the newest version of Empire and I had to put some modification in your empire's part as well. If I good remember in 
https://github.com/sensepost/liniaal/blob/f79f0241de65c85c56d55c6ce54ba70a129b01bd/empire/lib/listeners/http_mapi.py#L221

Look at original http listener
https://github.com/EmpireProject/Empire/blob/37c72f0428d68edc36d4e19ee3540770ef12d981/lib/listeners/http.py#L258

I had to add second argument (_launcher_) to _powershell_launcher_ function. Without this launcher could not be generated.

**Comment by staaldraad** [comment]
Using docker isn't always the best for this.. I thought I was using the container with the Empire folder mapped through, and testing with latest empire. Turns out I didn't and was still on the *2.0_beta* branch.

I've made the changes to the listener as required. I had to add the launcher as an option and then add the same change as you did above. I've merged this into master with commit b70cb05ff05814ade0b2e2123119ab5c1b7cca12

Tested and it's all working for me in testing. Only other issue I can think is that there are messages hanging around, I recommend a "flush" or using a new folder.

**Comment by n0clues** [comment]
Hi! No worries :) 

I flushed everything, started launcher without `-NoP -sta -NonI -W Hidden` but still without success (I don't see any messages on CMD on my "victim" machine:

![obraz](https://user-images.githubusercontent.com/5691550/29169663-78c9663e-7dd5-11e7-863a-1230d295f6af.png)

Empire with --debug 2 is silent like a fish as well:
![obraz](https://user-images.githubusercontent.com/5691550/29169676-8e6fa84a-7dd5-11e7-8d19-5943315b3bd5.png)

and here liniaal:
![obraz](https://user-images.githubusercontent.com/5691550/29169693-a1c10164-7dd5-11e7-9ad3-cbcd5e244dd7.png)

![obraz](https://user-images.githubusercontent.com/5691550/29169710-ba4064fa-7dd5-11e7-8d1f-6b950ff67d70.png)

It doesn't receive _PMPOST_ payload. I found the loop ends on condition in line 212:

https://github.com/sensepost/liniaal/blob/b70cb05ff05814ade0b2e2123119ab5c1b7cca12/liniaal.go#L212

**Comment by staaldraad** [comment]
It seems like it isn't completing the connection to Empire, because --debug 2 would show up any connections coming in.

Could you try with some output added on line 213:
```
	if err != nil {
            output(err.Error())
	    continue
      }
```

**Comment by n0clues** [comment]
Eh man, I don't know why I thought there is `err == nil` so I didn't output the `err `(why should I output the `nil`...) anyway it was indeed connection problem so I checked my Empire listeners one more time and what I realized my BindIP was  not equal to host (my big mistake!), after that I was few step further but it still didn't want to work.

What I noticed on my "victim" screen:
![obraz](https://user-images.githubusercontent.com/5691550/29177114-151aeba8-7dee-11e7-9e97-23f3c21f1414.png)

Do you know that? It's Windows 8.1 and Office 2013. For now I don't have possibility to test liniaal on Windows 10 (Maybe tomorrow I will have then I will test it).
Regarding this question box when I allowed access for a 10 minutes then I received agent in Empire:

![obraz](https://user-images.githubusercontent.com/5691550/29177291-a0f72290-7dee-11e7-8c88-c793effa8cb1.png)

Anyway this additional interaction from victim side puts this technique under a question mark.

**Comment by staaldraad** [comment]
Ah! Ok :smile:  When I looked back at your screenshot I noticed http and mapi had different IPs set, thought it might be a dual homed box. 

So for the next bit, that is an "AV problem" 

That is outlook's programmatic access protection. I'm assuming that host has no AV installed, or the AV is out dated? The default security for Outlook is to block programmatic access if the AV is outdated or not installed. Completely forgot about this. My theory is that in any corporate environment, what is "best practice"? Install AV of course! And as soon as AV is installed, Outlook becomes vulnerable.. I love the irony.

If you go to File -> Options -> Trust Center -> Trust Center Settings 
Then go to "Programmatic access" 
(you may need to start Outlook as an admin to change this setting)

![trustcenter](https://user-images.githubusercontent.com/4200832/29178904-37e9f962-7df3-11e7-8655-845aa60e9d53.png)


So I've been testing on Win10 and Office 2016 (insider channel) and it works. With win10 you get the benefit of Defender being installed/active by default. So you don't run into programmatic access warnings.

**Comment by n0clues** [comment]
Cool, thank you very much. I will confirm that when I test it on other configuration. 

Anyway I see you resolved the issue. The main mistake was on my side (`BindIP `in empire) but in mean time we found few other places to repair.

Thank you very much for your help!

**Comment by staaldraad** [comment]
Happy it's working and thanks so much for raising the issue. And helping squash those bugs.

If anything else pops, please let me know!

**Comment by n0clues** [comment]
I confirm that  on Windows 10 Outlook pop-ups the warning-box when Defender is disabled, When the Defender is enabled, victim doesn't see any boxes... nice 😆

**Comment by staaldraad** [comment]
AV to the rescue :rofl: 

The irony of this kills me
